name: facebook_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # firebase
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  
  # birthday date picker
  flutter_holo_date_picker: ^1.1.3

  # for providing icons
  font_awesome_flutter: ^10.6.0

  # formatting dates and timeago
  jiffy: ^6.2.2

  # generating ids for users
  uuid: ^4.3.3

  # state management
  flutter_riverpod: ^2.4.9

  # show toast message
  fluttertoast: ^8.2.4

  # pick images
  image_picker: ^1.0.7

  # play videos
  video_player: ^2.8.2

  # for displaying the stories
  story_view: ^0.16.0
  flutter_lints: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/